create table if not exists public.invitations (
  id text primary key,
  creator_id text not null,
  from_name text not null,
  to_name text not null,
  intro text default '',
  note text default '',
  status text not null default 'pending' check (status in ('pending', 'responded')),
  created_at timestamptz not null default now()
);

create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  invitation_id text not null unique references public.invitations(id) on delete cascade,
  food text default '',
  place text default '',
  time text default '',
  message text default '',
  reply text not null default 'accept',
  created_at timestamptz not null default now()
);

create index if not exists invitations_creator_id_created_at_idx
  on public.invitations (creator_id, created_at desc);

create index if not exists responses_invitation_id_idx
  on public.responses (invitation_id);

alter table public.invitations enable row level security;
alter table public.responses enable row level security;
